version: '3'
services:
  xo:
    build: .
    ports:
    - "8080:80"
    links:
    - redis
  redis:
    image: redis
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
